
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 4;
  public static final int GE = 14;
  public static final int PID = 39;
  public static final int REPEAT = 29;
  public static final int L = 11;
  public static final int FOR = 31;
  public static final int MINUS = 3;
  public static final int G = 12;
  public static final int WRITE = 37;
  public static final int E = 9;
  public static final int SEMICOLON = 17;
  public static final int COMMA = 16;
  public static final int BEGIN = 20;
  public static final int ENDFOR = 35;
  public static final int UNTIL = 30;
  public static final int PLUS = 2;
  public static final int ASSIGN = 15;
  public static final int IF = 22;
  public static final int ENDWHILE = 28;
  public static final int LE = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NUMBER = 38;
  public static final int MOD = 6;
  public static final int DECLARE = 19;
  public static final int FROM = 32;
  public static final int TIMES = 5;
  public static final int COLON = 18;
  public static final int ENDIF = 25;
  public static final int ELSE = 24;
  public static final int READ = 36;
  public static final int TO = 33;
  public static final int WHILE = 26;
  public static final int THEN = 23;
  public static final int NE = 10;
  public static final int OPEN = 7;
  public static final int END = 21;
  public static final int DOWNTO = 34;
  public static final int CLOSE = 8;
  public static final int DO = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "TIMES",
  "MOD",
  "OPEN",
  "CLOSE",
  "E",
  "NE",
  "L",
  "G",
  "LE",
  "GE",
  "ASSIGN",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "DECLARE",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDWHILE",
  "REPEAT",
  "UNTIL",
  "FOR",
  "FROM",
  "TO",
  "DOWNTO",
  "ENDFOR",
  "READ",
  "WRITE",
  "NUMBER",
  "PID"
  };
}

